# @package _global_
# TensorBoard Logger 配置

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${hydra:runtime.output_dir}
  name: ${run.name}
  version: null
  log_graph: false
  default_hp_metric: true
